name: Build, Test, Push

on:
  schedule:
    - cron: '0 10 * * 0' # Every Sunday at 10AM
  push:
    branches:
      - master
      - develop
      - feature/*
    tags:
      - 'v*.*.*'
  workflow_dispatch: # Allow manually triggering a build

defaults:
  run:
    shell: bash

env:
  DOCKSAL_VERSION: develop
  # Setting these while testing locally may result in data loss, so only use in CI.
  DOCKSAL_DNS_DISABLED: 1
  DOCKSAL_DNS_DOMAIN: docksal.site
  EVENT_NAME: '${{ github.event_name }}'
  REPO: docksal/mysql
  LATEST_VERSION: 8.0

jobs:
  default:
    name: 'Build, test, and push'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            version: '5.7'
            from: 'mysql:5.7'
          -
            version: '8.0'
            from: 'mysql:8.0'

    env:
      VERSION: ${{ matrix.version }}
      FROM: ${{ matrix.from }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Check Docker
        run: |
          docker version
          docker info
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Install BATS (tests)
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
          bats -v
      -
        name: Install Docksal
        run: curl -sSL http://get.docksal.io | bash
      -
        name: fin version
        run: fin version
      -
        name: fin sysinfo
        run: fin sysinfo
      -
        name: Build and test
        run: |
          make
          make test
      -
        name: Source name
        id: source_name
        run: |
          echo "::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}"
          echo "::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}"
          if [[ ${{ github.event.ref }} =~ ^refs/tags/ ]]; then
              echo "::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}"
          else
              echo "::set-output name=SOURCE_TAG::"
          fi
      -
        name: Release on success
        if: |
          success() &&
          (
            github.ref == 'refs/heads/develop' ||
            github.ref == 'refs/heads/master' ||
            startsWith(github.ref, 'refs/tags')
          )
        run: make release
        env:
          SOURCE_NAME: '${{ steps.source_name.outputs.SOURCE_NAME }}'
          SOURCE_BRANCH: '${{ steps.source_name.outputs.SOURCE_BRANCH }}'
          SOURCE_TAG: '${{ steps.source_name.outputs.SOURCE_TAG }}'
      -
        name: Log on failure
        if: ${{ failure() }}
        run: make logs
